CREATE TABLE IF NOT EXISTS "study_tool_course" (
	"record_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "study_tool_course_record_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"course_name" varchar(256),
	"course_desc" text DEFAULT '',
	"is_active" boolean DEFAULT true,
	"user_id" varchar(256),
	"uploaded_files" json DEFAULT '[]',
	"uploaded_files_count" integer DEFAULT 0,
	"uploaded_files_size" integer DEFAULT 0,
	"generated_files" json DEFAULT '[]',
	"generated_files_count" integer DEFAULT 0,
	"generated_files_size" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "study_tool_files" (
	"record_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "study_tool_files_record_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"file_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar(256),
	"course_id" uuid NOT NULL,
	"file_name" varchar(256),
	"file_size" integer,
	"file_url" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "study_tool_todo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "study_tool_todo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"done" boolean DEFAULT false,
	"user_id" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "study_tool_todo" USING btree ("title");